<html>
  <head>
    <title>Coachassistant API Documentation version $version$</title>
    <link rel="stylesheet" type="text/css" href="doc-template/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="doc-template/prettify.css">
    <link rel="stylesheet" type="text/css" href="doc-template/docs.css">
    <script type="text/javascript" src="doc-template/jquery-nightly.js"></script>
    <script type="text/javascript" src="doc-template/bootstrap-modal.js"></script>
    <script type="text/javascript" src="doc-template/prettify.js"></script>
    <script type="text/javascript" src="doc-template/docs.js"></script>
  </head>
  <body>
    <div class="container-fluid">
      <div class="sidebar">
        <p>Coachassistant API $version$</p>
        <div class="page-header">
          <h1>Resources</h1>
        </div>
        <ul>
          <li>
          $listing; separator="</li><li>"$
          </li>
        </ul>
      </div>
      <div class="content">

        <br/><br/>
        $resources$
      </div>
    </div>
  </body>
</html>
